/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.lvlv.supersearch;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int add_search_button=0x7f050007;
        public static final int go_button=0x7f050002;
        public static final int location_input=0x7f050005;
        public static final int manage_button=0x7f050003;
        public static final int name_input=0x7f050004;
        public static final int search_input=0x7f050001;
        public static final int search_location=0x7f050000;
        public static final int term_input=0x7f050006;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int modifysearches=0x7f030001;
    }
    public static final class string {
        public static final int add_search_label=0x7f040007;
        public static final int app_name=0x7f040000;
        public static final int go_label=0x7f040001;
        public static final int location_hint=0x7f040005;
        public static final int manage_label=0x7f040008;
        public static final int modify_title=0x7f040002;
        public static final int name_hint=0x7f040004;
        public static final int search_hint=0x7f040003;
        public static final int term_hint=0x7f040006;
    }
}
